package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

//
// =============================
// Request / Response Structures
// =============================
//

// ReduceReq represents the JSON input sent to the /reduce endpoint.
// It contains a list of S3 URLs generated by mapper tasks.
type ReduceReq struct {
	MapURLs []string `json:"map_urls"`
}

// ReduceResp is the JSON response returned by the reducer.
// It tells the client where the final merged result is stored.
type ReduceResp struct {
	ResultURL string `json:"result_url"`
}

//
// =============================
// Utility Functions
// =============================
//

// writeJSON is a helper to send JSON responses with a status code.
func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// parseS3URL extracts the bucket and key from a URL of the form:
// s3://bucket-name/path/to/file
func parseS3URL(url string) (bucket, key string, ok bool) {
	if !strings.HasPrefix(url, "s3://") {
		return "", "", false
	}
	rest := strings.TrimPrefix(url, "s3://")
	parts := strings.SplitN(rest, "/", 2)
	if len(parts) != 2 {
		return "", "", false
	}
	return parts[0], parts[1], true
}

// readAll reads all bytes from an io.Reader (e.g., S3 object body).
func readAll(r io.Reader) ([]byte, error) {
	return io.ReadAll(r)
}

//
// =============================
// Main Application
// =============================
//

func main() {
	// Read port from environment variable (useful in ECS/container)
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	ctx := context.Background()

	// Load AWS configuration (credentials, region, etc.)
	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		log.Fatalf("load aws config: %v", err)
	}

	// Create an S3 client
	s3c := s3.NewFromConfig(cfg)

	//
	// -----------------------------
	// /reduce HTTP endpoint
	// -----------------------------
	//
	http.HandleFunc("/reduce", func(w http.ResponseWriter, r *http.Request) {

		// Only allow POST requests
		if r.Method != http.MethodPost {
			writeJSON(w, 405, map[string]any{"error": "method not allowed"})
			return
		}

		// Decode incoming JSON request body
		var req ReduceReq
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeJSON(w, 400, map[string]any{"error": "invalid json", "detail": err.Error()})
			return
		}

		// Validate input
		if len(req.MapURLs) == 0 {
			writeJSON(w, 400, map[string]any{"error": "map_urls required"})
			return
		}

		// merged will store the final word counts
		merged := map[string]int{}

		var bucket string
		var runID string

		// Loop over each mapper output file
		for _, url := range req.MapURLs {

			// Parse S3 bucket + key from URL
			b, k, ok := parseS3URL(url)
			if !ok {
				writeJSON(w, 400, map[string]any{"error": "invalid map_url", "url": url})
				return
			}
			bucket = b

			// Extract run ID from key path
			// Example key: maps/run-XXXX/map-0.json
			parts := strings.Split(k, "/")
			if len(parts) >= 2 {
				runID = strings.TrimPrefix(parts[1], "run-")
			}

			// Download mapper output from S3
			obj, err := s3c.GetObject(ctx, &s3.GetObjectInput{
				Bucket: &b,
				Key:    &k,
			})
			if err != nil {
				writeJSON(w, 500, map[string]any{"error": "s3 get_object failed", "detail": err.Error()})
				return
			}

			// Read object body
			data, err := readAll(obj.Body)
			obj.Body.Close()
			if err != nil {
				writeJSON(w, 500, map[string]any{"error": "read body failed", "detail": err.Error()})
				return
			}

			// Each mapper output is expected to be:
			// { "word1": count, "word2": count, ... }
			var counts map[string]int
			if err := json.Unmarshal(data, &counts); err != nil {
				writeJSON(w, 500, map[string]any{"error": "invalid json in map output", "detail": err.Error()})
				return
			}

			// Merge counts into global result
			for word, c := range counts {
				merged[word] += c
			}
		}

		// Construct final output key in S3
		outKey := fmt.Sprintf("reduce/run-%s/result.json", runID)

		// Convert merged map to JSON
		body, _ := json.Marshal(merged)

		// Upload final result to S3
		_, err := s3c.PutObject(ctx, &s3.PutObjectInput{
			Bucket: &bucket,
			Key:    &outKey,
			Body:   strings.NewReader(string(body)),
		})
		if err != nil {
			writeJSON(w, 500, map[string]any{"error": "s3 put_object failed", "detail": err.Error()})
			return
		}

		// Return success response with final S3 location
		writeJSON(w, 200, ReduceResp{
			ResultURL: fmt.Sprintf("s3://%s/%s", bucket, outKey),
		})
	})

	//
	// -----------------------------
	// Health Check Endpoint
	// -----------------------------
	//
	http.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, 200, map[string]any{"ok": true})
	})

	log.Printf("reducer listening on :%s", port)
	log.Fatal(http.ListenAndServe("0.0.0.0:"+port, nil))
}
